/**
 * Curated "best ~12" exercises per muscle group AND per subcategory, fed to the
 * AI workout-plan prompt so it picks well-known, widely-available movements
 * instead of the raw array order.
 *
 * Selection criteria (gym-community popularity, not array order):
 *   - most commonly programmed & practised movements,
 *   - broadly liked / staple in typical commercial gyms,
 *   - available with standard equipment (barbell, dumbbell, cable, machine,
 *     plus a few key bodyweight moves).
 * Ordered heavy-compound → staple isolation → bodyweight within each group.
 *
 * HARD RULE: every name here MUST exist verbatim in EXERCISES_DB (src/lib/
 * exercises.ts) — names are the canonical IDs used for logging/pinning/tutorials.
 * aiPlan.ts filters this list against EXERCISES_DB defensively, and
 * scripts-style validation (see the assert in generateAiPlan's module) drops any
 * that don't match, so a typo can never inject a non-canonical name.
 *
 * Subcategories are first-class here: legs is split into quads/hamstrings/
 * glutes/calves/abductors/adductors, and back into lats/upper-back/traps/
 * lower-back — each gets its own curated 12, matching MUSCLE_SUBCATEGORIES.
 */
export const AI_CATALOG_GROUPS: { group: string; exercises: string[] }[] = [
  {
    group: "Chest",
    exercises: [
      "Barbell Bench Press",
      "Barbell Incline Bench Press",
      "Dumbbell Bench Press",
      "Dumbbell Incline Bench Press",
      "Machine Bench Press",
      "Plate-Loaded Incline Chest Press",
      "Machine Chest Fly",
      "Cable Crossover Fly",
      "Low Cable Chest Fly",
      "Dumbbell Fly",
      "Chest Dip",
      "Push Up",
    ],
  },
  {
    group: "Back — Lats",
    exercises: [
      "Lat Pulldown",
      "Pull Up",
      "Chin Up",
      "Lat Pulldown Neutral Grip",
      "Close Grip Pulldown",
      "V Bar Pulldown",
      "Single Arm Lat Pulldown",
      "Machine Lat Pulldown",
      "Assisted Pull up",
      "Reverse Grip Pulldown",
      "Straight Arm Pulldown",
      "Plate-Loaded Pullover",
    ],
  },
  {
    group: "Back — Upper Back & Rows",
    exercises: [
      "Barbell Row",
      "Dumbbell Row",
      "Cable Row",
      "T Bar Row",
      "Pendlay Row",
      "Chest Supported T Row Neutral Grip",
      "Machine Row",
      "Single Arm Cable Row",
      "Incline Dumbbell Row",
      "Landmine Row",
      "Meadows Row",
      "Inverted Row",
    ],
  },
  {
    group: "Traps",
    exercises: [
      "Barbell Shrug",
      "Dumbbell Shrug",
      "Cable Shrug",
      "Trap Bar Shrug",
      "Smith Machine Shrug",
      "Seated Dumbbell Shrug",
      "Behind the Back Barbell Shrug",
      "Barbell Upright Row",
      "Dumbbell Upright Row",
      "Cable Upright Row",
      "Farmer's Carry",
      "Power Shrug",
    ],
  },
  {
    group: "Lower Back",
    exercises: [
      "Back Extension",
      "45-Degree Back Extension",
      "Weighted Back Extension",
      "Machine Back Extension",
      "Reverse Hyperextension",
      "Rack Pulls",
      "Seated Good Morning",
      "Jefferson Curl",
      "Superman",
      "Alternating Superman",
      "Bird Dog",
      "Stability Ball Back Extension",
    ],
  },
  {
    group: "Shoulders",
    exercises: [
      "Barbell Shoulder Press",
      "Dumbbell Shoulder Press",
      "Seated Barbell Shoulder Press",
      "Arnold Press",
      "Machine Shoulder Press",
      "Dumbbell Lateral Raise",
      "Cable Lateral Raise",
      "Machine Lateral Raise",
      "Cable Face Pull",
      "Machine Reverse Fly",
      "Cable Reverse Fly",
      "Dumbbell Front Raise",
    ],
  },
  {
    group: "Biceps",
    exercises: [
      "Barbell Curl",
      "Dumbbell Bicep Curl",
      "Hammer Curls",
      "EZ Bar Curl",
      "Preacher Curl",
      "Incline Dumbbell Curl",
      "Cable Bicep Curl",
      "Cable Hammer Curl",
      "Dumbbell Concentration Curl",
      "Spider Curls",
      "Machine Bicep Curl",
      "Seated Dumbbell Curl",
    ],
  },
  {
    group: "Triceps",
    exercises: [
      "Tricep Pushdown",
      "Tricep Pushdown V Bar",
      "Cable Rope Tricep Extension",
      "Cable Overhead Tricep Extension (rope)",
      "Close Grip Bench Press",
      "EZ Bar Skullcrusher",
      "Dumbbell Skullcrusher",
      "EZ Bar Overhead Tricep Extension",
      "Machine Tricep Extension",
      "Tricep Dip",
      "Bench Dip",
      "Dumbbell Kickbacks",
    ],
  },
  {
    group: "Forearms",
    exercises: [
      "Palms Up Barbell Wrist Curl",
      "Palms Down Barbell Wrist Curl",
      "Palms Up Dumbbell Wrist Curl",
      "Palms Down Dumbbell Wrist Curl",
      "Reverse Wrist Curl",
      "Cable Wrist Curl",
      "Behind the Back Wrist Curl",
      "Wrist Roller",
      "Dead Hang",
      "Farmer's Carry (Heavy)",
      "Plate Pinch Hold",
      "Gripper Squeeze",
    ],
  },
  {
    group: "Abs & Core",
    exercises: [
      "Hanging Leg Raise",
      "Hanging Knee Raise",
      "Rope Crunch",
      "Ab Wheel Rollout",
      "Bicycle Crunch",
      "Crunches",
      "Reverse Crunch",
      "Leg Raise",
      "Russian Twist",
      "Plank",
      "Side Plank",
      "Mountain Climber",
    ],
  },
  {
    group: "Quads",
    exercises: [
      "Back Squat",
      "Front Squat",
      "Leg Press",
      "Hack Squat",
      "Smith Machine Squat",
      "Goblet Squat",
      "Bulgarian Split Squat",
      "Barbell Lunge",
      "Walking Lunge",
      "Dumbbell Lunge",
      "Dumbbell Step Up",
      "Leg Extension",
    ],
  },
  {
    group: "Hamstrings",
    exercises: [
      "Barbell Romanian Deadlift",
      "Deadlift",
      "Dumbbell Romanian Deadlift",
      "Stiff Legged Deadlift",
      "Sumo Deadlift",
      "Trap Bar Deadlift",
      "Single Leg Romanian Deadlift",
      "Good Morning",
      "Seated Leg Curl",
      "Lying Hamstring Curl",
      "Plate-Loaded Standing Leg Curl",
      "Single Leg Lying Hamstring Curl",
    ],
  },
  {
    group: "Glutes",
    exercises: [
      "Barbell Hip Thrust",
      "Barbell Glute Bridge",
      "Dumbbell Hip Thrust",
      "Smith Machine Hip Thrust",
      "Cable Kickback",
      "Cable Pull Through",
      "Machine Glute Kickback",
      "Machine Standing Hip Extension",
      "Kettlebell Swing",
      "Glute Ham Raise",
      "Single Leg Glute Bridge",
      "Mini Band Kickbacks",
    ],
  },
  {
    group: "Calves",
    exercises: [
      "Standing Machine Calf Raise",
      "Seated Calf Extension",
      "Calf Press on Leg Press",
      "Smith Machine Calf Raise",
      "Plate-Loaded Standing Calf Raise",
      "Plate-Loaded Seated Calf Raise",
      "Dumbbell Calf Raise",
      "Barbell Calf Raise",
      "Single Leg Standing Calf Raise",
      "Seated Dumbbell Calf Raise",
      "Donkey Calf Raise",
      "Calf Raise",
    ],
  },
  {
    group: "Abductors",
    exercises: [
      "Machine Abduction",
      "Cable Hip Abduction",
      "Cable Standing Hip Abduction",
      "Multi Hip Abduction",
      "Banded Seated Abduction",
      "Banded Side Lying Hip Abduction",
      "Lateral Band Walk",
      "Clamshells",
      "Fire Hydrant",
      "Standing Side Leg Raise",
      "Curtsy Lunge",
      "Side Plank Hip Abduction",
    ],
  },
  {
    group: "Adductors",
    exercises: [
      "Machine Adduction",
      "Cable Hip Adduction",
      "Multi Hip Adduction",
      "Copenhagen Plank",
      "Side Lunge",
      "Sumo Squat (Wide Stance)",
      "Adductor Squeeze (Ball)",
      "Lying Adduction Leg Raise",
      "Banded Adduction",
    ],
  },
];
