import assert from "node:assert";
import { getExerciseThumbnail, hasExerciseThumbnail, normalizeExerciseKey } from "./exerciseImages.ts";

// Test 1: Normalization
assert.strictEqual(normalizeExerciseKey("Barbell Bench Press"), "barbell bench press");
assert.strictEqual(normalizeExerciseKey("  Incline   Barbell Bench Press  "), "incline barbell bench press");
assert.strictEqual(normalizeExerciseKey("T-Bar Row"), "t bar row");
assert.strictEqual(normalizeExerciseKey("Close-Grip Bench Press"), "close grip bench press");

// Test 2: Approved exercises return exact image path
assert.strictEqual(getExerciseThumbnail("Barbell Bench Press"), "/exercises/barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Barbell Bench Press"), "/exercises/incline_barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Bench Press"), "/exercises/dumbbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Dumbbell Bench Press"), "/exercises/incline_dumbbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Machine Bench Press"), "/exercises/machine_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Crossover Fly"), "/exercises/cable_crossover_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Back Squat"), "/exercises/back_squat.jpg");
// Batch 1 additions
assert.strictEqual(getExerciseThumbnail("Plate Loaded Chest Press"), "/exercises/plate_loaded_chest_press.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Fly"), "/exercises/dumbbell_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Chest Dip"), "/exercises/chest_dip.jpg");
assert.strictEqual(getExerciseThumbnail("Push Up"), "/exercises/push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Plyometric Push-ups"), "/exercises/plyometric_push_ups.jpg");
assert.strictEqual(getExerciseThumbnail("Deadlift"), "/exercises/deadlift.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Row"), "/exercises/barbell_row.jpg");
assert.strictEqual(getExerciseThumbnail("Pendlay Row"), "/exercises/pendlay_row.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Row"), "/exercises/dumbbell_row.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Row"), "/exercises/cable_row.jpg");
// Batch 1 & 2 additions
assert.strictEqual(getExerciseThumbnail("Decline Barbell Bench Press"), "/exercises/decline_barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Decline Dumbbell Bench Press"), "/exercises/decline_dumbbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Pull Up"), "/exercises/pull_up.jpg");
assert.strictEqual(getExerciseThumbnail("Lat Pulldown"), "/exercises/lat_pulldown.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Pullover"), "/exercises/dumbbell_pullover.jpg");
assert.strictEqual(getExerciseThumbnail("Inverted Row"), "/exercises/inverted_row.jpg");
assert.strictEqual(getExerciseThumbnail("Front Squat"), "/exercises/front_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Leg Press"), "/exercises/leg_press.jpg");
assert.strictEqual(getExerciseThumbnail("Hack Squat"), "/exercises/hack_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Goblet Squat"), "/exercises/goblet_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Romanian Deadlift"), "/exercises/romanian_deadlift.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Romanian Deadlift"), "/exercises/dumbbell_romanian_deadlift.jpg");
assert.strictEqual(getExerciseThumbnail("Bulgarian Split Squat"), "/exercises/bulgarian_split_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Walking Lunge"), "/exercises/walking_lunge.jpg");
assert.strictEqual(getExerciseThumbnail("Leg Extension"), "/exercises/leg_extension.jpg");
assert.strictEqual(getExerciseThumbnail("Lying Hamstring Curl"), "/exercises/lying_hamstring_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Seated Leg Curl"), "/exercises/seated_leg_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Standing Calf Raise"), "/exercises/standing_calf_raise.jpg");
assert.strictEqual(getExerciseThumbnail("Seated Calf Raise"), "/exercises/seated_calf_raise.jpg");
assert.strictEqual(getExerciseThumbnail("T-Bar Row"), "/exercises/t_bar_row.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Hip Thrust"), "/exercises/barbell_hip_thrust.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Hip Thrust"), "/exercises/dumbbell_hip_thrust.jpg");
assert.strictEqual(getExerciseThumbnail("Box Jump"), "/exercises/box_jump.jpg");
assert.strictEqual(getExerciseThumbnail("Sled Push"), "/exercises/sled_push.jpg");
assert.strictEqual(getExerciseThumbnail("TRX Pistol Squat"), "/exercises/trx_pistol_squat.jpg");

// Test 3: Common aliases resolve to correct approved asset
assert.strictEqual(getExerciseThumbnail("T-Bar Row"), "/exercises/t_bar_row.jpg");
assert.strictEqual(getExerciseThumbnail("Landmine Row"), "/exercises/t_bar_row.jpg");
assert.strictEqual(getExerciseThumbnail("Hip Thrust"), "/exercises/barbell_hip_thrust.jpg");
assert.strictEqual(getExerciseThumbnail("Box Jumps"), "/exercises/box_jump.jpg");
assert.strictEqual(getExerciseThumbnail("Prowler Push"), "/exercises/sled_push.jpg");
assert.strictEqual(getExerciseThumbnail("Pistol Squat"), "/exercises/trx_pistol_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Bench Press"), "/exercises/barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Flat Bench Press"), "/exercises/barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Incline Bench Press"), "/exercises/incline_barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Incline Bench Press"), "/exercises/incline_dumbbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Squat"), "/exercises/back_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Back Squat"), "/exercises/back_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Squats"), "/exercises/back_squat.jpg");
assert.strictEqual(getExerciseThumbnail("Pushups"), "/exercises/push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Clapping Push Up"), "/exercises/plyometric_push_ups.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Deadlift"), "/exercises/deadlift.jpg");
assert.strictEqual(getExerciseThumbnail("Seated Cable Row"), "/exercises/cable_row.jpg");
assert.strictEqual(getExerciseThumbnail("Decline Bench Press"), "/exercises/decline_barbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Pullups"), "/exercises/pull_up.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Lat Pulldown"), "/exercises/lat_pulldown.jpg");
assert.strictEqual(getExerciseThumbnail("Australian Pull Up"), "/exercises/inverted_row.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Front Squat"), "/exercises/front_squat.jpg");
assert.strictEqual(getExerciseThumbnail("45 Degree Leg Press"), "/exercises/leg_press.jpg");
// Batch 3 Shoulder assertions
assert.strictEqual(getExerciseThumbnail("Barbell Shoulder Press"), "/exercises/barbell_shoulder_press.jpg");
assert.strictEqual(getExerciseThumbnail("Overhead Press"), "/exercises/barbell_shoulder_press.jpg");
assert.strictEqual(getExerciseThumbnail("OHP"), "/exercises/barbell_shoulder_press.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Shoulder Press"), "/exercises/dumbbell_shoulder_press.jpg");
assert.strictEqual(getExerciseThumbnail("DB Shoulder Press"), "/exercises/dumbbell_shoulder_press.jpg");
assert.strictEqual(getExerciseThumbnail("Arnold Press"), "/exercises/arnold_press.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Lateral Raise"), "/exercises/dumbbell_lateral_raise.jpg");
assert.strictEqual(getExerciseThumbnail("Side Lateral Raise"), "/exercises/dumbbell_lateral_raise.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Front Raise"), "/exercises/dumbbell_front_raise.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Face Pull"), "/exercises/cable_face_pull.jpg");
assert.strictEqual(getExerciseThumbnail("Face Pulls"), "/exercises/cable_face_pull.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Reverse Fly"), "/exercises/cable_reverse_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Rear Delt Fly"), "/exercises/cable_reverse_fly.jpg");
// Batch 3 Arm assertions
assert.strictEqual(getExerciseThumbnail("Barbell Curl"), "/exercises/barbell_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Bicep Curl"), "/exercises/barbell_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Bicep Curl"), "/exercises/dumbbell_bicep_curl.jpg");
assert.strictEqual(getExerciseThumbnail("DB Curl"), "/exercises/dumbbell_bicep_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Hammer Curls"), "/exercises/hammer_curls.jpg");
assert.strictEqual(getExerciseThumbnail("Hammer Curl"), "/exercises/hammer_curls.jpg");
assert.strictEqual(getExerciseThumbnail("Preacher Curl"), "/exercises/preacher_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Tricep Pushdown"), "/exercises/tricep_pushdown.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Tricep Pushdown"), "/exercises/tricep_pushdown.jpg");
assert.strictEqual(getExerciseThumbnail("EZ Bar Skullcrusher"), "/exercises/ez_bar_skullcrusher.jpg");
assert.strictEqual(getExerciseThumbnail("Skullcrushers"), "/exercises/ez_bar_skullcrusher.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Overhead Tricep Extension"), "/exercises/dumbbell_overhead_tricep_extension.jpg");
assert.strictEqual(getExerciseThumbnail("Overhead Tricep Extension"), "/exercises/dumbbell_overhead_tricep_extension.jpg");
assert.strictEqual(getExerciseThumbnail("Handstand Push-ups"), "/exercises/handstand_push_ups.jpg");
assert.strictEqual(getExerciseThumbnail("Handstand Push Up"), "/exercises/handstand_push_ups.jpg");
assert.strictEqual(getExerciseThumbnail("HSPU"), "/exercises/handstand_push_ups.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Dumbbell Curl"), "/exercises/incline_dumbbell_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Curl"), "/exercises/incline_dumbbell_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Concentration Curl"), "/exercises/dumbbell_concentration_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Concentration Curl"), "/exercises/dumbbell_concentration_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Bicep Curl"), "/exercises/cable_bicep_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Curl"), "/exercises/cable_bicep_curl.jpg");
assert.strictEqual(getExerciseThumbnail("Close Grip Bench Press"), "/exercises/close_grip_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("CGBP"), "/exercises/close_grip_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Bench Dip"), "/exercises/bench_dip.jpg");
assert.strictEqual(getExerciseThumbnail("Tricep Dip"), "/exercises/bench_dip.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Kickbacks"), "/exercises/dumbbell_kickbacks.jpg");
assert.strictEqual(getExerciseThumbnail("DB Kickback"), "/exercises/dumbbell_kickbacks.jpg");
assert.strictEqual(getExerciseThumbnail("Dumbbell Shrug"), "/exercises/dumbbell_shrug.jpg");
assert.strictEqual(getExerciseThumbnail("DB Shrug"), "/exercises/dumbbell_shrug.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Shrug"), "/exercises/barbell_shrug.jpg");
assert.strictEqual(getExerciseThumbnail("Shrugs"), "/exercises/barbell_shrug.jpg");
assert.strictEqual(getExerciseThumbnail("Farmer's Carry"), "/exercises/farmers_carry.jpg");
assert.strictEqual(getExerciseThumbnail("Farmers Walk"), "/exercises/farmers_carry.jpg");
assert.strictEqual(getExerciseThumbnail("Alternating Battle Rope"), "/exercises/alternating_battle_rope.jpg");
assert.strictEqual(getExerciseThumbnail("Battle Ropes"), "/exercises/alternating_battle_rope.jpg");
assert.strictEqual(getExerciseThumbnail("Battle Rope"), "/exercises/alternating_battle_rope.jpg");
assert.strictEqual(getExerciseThumbnail("Plank"), "/exercises/plank.jpg");
assert.strictEqual(getExerciseThumbnail("Forearm Plank"), "/exercises/plank.jpg");
assert.strictEqual(getExerciseThumbnail("Front Plank"), "/exercises/plank.jpg");
assert.strictEqual(getExerciseThumbnail("Planks"), "/exercises/plank.jpg");
assert.strictEqual(getExerciseThumbnail("Side Plank"), "/exercises/side_plank.jpg");
assert.strictEqual(getExerciseThumbnail("Side Planks"), "/exercises/side_plank.jpg");
assert.strictEqual(getExerciseThumbnail("Ab Wheel Rollout"), "/exercises/ab_wheel_rollout.jpg");
assert.strictEqual(getExerciseThumbnail("Ab Rollout"), "/exercises/ab_wheel_rollout.jpg");
assert.strictEqual(getExerciseThumbnail("Hanging Leg Raise"), "/exercises/hanging_leg_raise.jpg");
assert.strictEqual(getExerciseThumbnail("Hanging Knee Raise"), "/exercises/hanging_knee_raise.jpg");
assert.strictEqual(getExerciseThumbnail("Russian Twist"), "/exercises/russian_twist.jpg");
assert.strictEqual(getExerciseThumbnail("Russian Twists"), "/exercises/russian_twist.jpg");
assert.strictEqual(getExerciseThumbnail("Bicycle Crunch"), "/exercises/bicycle_crunch.jpg");
assert.strictEqual(getExerciseThumbnail("Bicycle Crunches"), "/exercises/bicycle_crunch.jpg");
assert.strictEqual(getExerciseThumbnail("Kettlebell Swing"), "/exercises/kettlebell_swing.jpg");
assert.strictEqual(getExerciseThumbnail("Kettlebell Swings"), "/exercises/kettlebell_swing.jpg");
assert.strictEqual(getExerciseThumbnail("Mountain Climber"), "/exercises/mountain_climber.jpg");
assert.strictEqual(getExerciseThumbnail("Mountain Climbers"), "/exercises/mountain_climber.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Wood Chop High to Low"), "/exercises/cable_wood_chop.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Wood Chop"), "/exercises/cable_wood_chop.jpg");
assert.strictEqual(getExerciseThumbnail("Woodchoppers"), "/exercises/cable_wood_chop.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Wood Chop Low to High"), "/exercises/cable_wood_chop_low_to_high.jpg");
assert.strictEqual(getExerciseThumbnail("Wood Chop Low to High"), "/exercises/cable_wood_chop_low_to_high.jpg");
assert.strictEqual(getExerciseThumbnail("Burpee"), "/exercises/burpee.jpg");
assert.strictEqual(getExerciseThumbnail("Burpees"), "/exercises/burpee.jpg");
assert.strictEqual(getExerciseThumbnail("Rope Crunch"), "/exercises/rope_crunch.jpg");
assert.strictEqual(getExerciseThumbnail("Cable Crunch"), "/exercises/rope_crunch.jpg");
assert.strictEqual(getExerciseThumbnail("Hollow Body Hold"), "/exercises/hollow_body_hold.jpg");
assert.strictEqual(getExerciseThumbnail("Hollow Body"), "/exercises/hollow_body_hold.jpg");
assert.strictEqual(getExerciseThumbnail("Crunches"), "/exercises/crunches.jpg");
assert.strictEqual(getExerciseThumbnail("Crunch"), "/exercises/crunches.jpg");
assert.strictEqual(getExerciseThumbnail("Bear Crawl Hold"), "/exercises/bear_crawl_hold.jpg");
assert.strictEqual(getExerciseThumbnail("Bear Plank"), "/exercises/bear_crawl_hold.jpg");
assert.strictEqual(getExerciseThumbnail("Iron Bridge"), "/exercises/iron_bridge.jpg");
// Glute Bridge is its own exercise, not Iron Bridge or a hip thrust: no picture until it has one.
assert.strictEqual(getExerciseThumbnail("Glute Bridge"), null);
assert.strictEqual(getExerciseThumbnail("Glute Bridge Hold"), null);
assert.strictEqual(getExerciseThumbnail("Medicine Ball Slams"), "/exercises/medicine_ball_slams.jpg");
assert.strictEqual(getExerciseThumbnail("Med Ball Slam"), "/exercises/medicine_ball_slams.jpg");
assert.strictEqual(getExerciseThumbnail("Renegade Row"), "/exercises/renegade_row.jpg");
assert.strictEqual(getExerciseThumbnail("Renegade Rows"), "/exercises/renegade_row.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Push Up"), "/exercises/incline_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Pushups"), "/exercises/incline_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Decline Push Up"), "/exercises/decline_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Decline Pushups"), "/exercises/decline_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Diamond Push Up"), "/exercises/diamond_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Diamond Pushups"), "/exercises/diamond_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Close Grip Push Up"), "/exercises/close_grip_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Floor Press"), "/exercises/floor_press.jpg");
assert.strictEqual(getExerciseThumbnail("Barbell Floor Press"), "/exercises/floor_press.jpg");
assert.strictEqual(getExerciseThumbnail("Machine Chest Fly"), "/exercises/machine_chest_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Pec Deck"), "/exercises/machine_chest_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Dumbbell Fly"), "/exercises/incline_dumbbell_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Fly"), "/exercises/incline_dumbbell_fly.jpg");
assert.strictEqual(getExerciseThumbnail("Wide Push Up"), "/exercises/wide_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Wide Grip Pushups"), "/exercises/wide_push_up.jpg");
assert.strictEqual(getExerciseThumbnail("Single Arm Dumbbell Bench Press"), "/exercises/single_arm_dumbbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Single Arm DB Bench Press"), "/exercises/single_arm_dumbbell_bench_press.jpg");
assert.strictEqual(getExerciseThumbnail("Plate-Loaded Incline Chest Press"), "/exercises/plate_loaded_incline_chest_press.jpg");
assert.strictEqual(getExerciseThumbnail("Incline Plate Loaded Chest Press"), "/exercises/plate_loaded_incline_chest_press.jpg");

// Test 4: hasExerciseThumbnail helper
assert.strictEqual(hasExerciseThumbnail("Barbell Bench Press"), true);
assert.strictEqual(hasExerciseThumbnail("Back Squat"), true);
assert.strictEqual(hasExerciseThumbnail("Some Unknown Move"), false);

// Test 5: Fallback behavior for ungenerated exercises or empty string
assert.strictEqual(getExerciseThumbnail("Non Existent Move 123"), null);
assert.strictEqual(getExerciseThumbnail(""), null);

console.log("✓ exerciseImages.test.ts: all assertions passed");
