export const EXERCISES_DB: Record<string, string[]> = {
  legs: [],
  biceps: [
    "Barbell Curl",
    "Dumbbell Bicep Curl",
    "EZ Bar Curl",
    "Seated Dumbbell Curl",
    "Cable Hammer Curl",
    "Dumbbell Concentration Curl",
    "Hammer Curls",
    "Incline Dumbbell Curl",
    "Incline Hammer Curl",
    "Preacher Curl",
    "Single Arm Cross Body Cable Curl",
    "Single Arm Preacher Curl",
    "Spider Curls",
    "Behind the Back Cable Bicep Curl",
    "Cable Bicep Curl",
    "Cable Double Arm Bayesian Curl",
    "Cable Double Bicep Curl",
    "Cable Potty Curls",
    "Close Grip EZ Bar Curl",
    "Cross Body Hammer Curls",
    "Dumbbell Drag Curl",
    "High Cable Bicep Curl",
    "Incline EZ Bar Curl",
    "Machine Bicep Curl",
    "Machine Preacher Curl",
    "Plate-Loaded Preacher Curl",
    "Single Arm Cable Bicep Curl",
    "Waiter Curls",
    "Bicep Curl to Shoulder Press",
    "Dumbbell Reverse Curl",
    "Loop Band Bicep Curl",
    "Loop Band Hammer Curl",
    "Reverse Barbell Curl",
    "TRX Bicep Curl",
    "Zottman Curl",
    "Zottman Preacher Curl"
  ],
  back: [],
  back_lats: [
    "Chin Up",
    "Pull Up",
    "Assisted Pull up",
    "Assisted Wide Grip Pull Up",
    "Assisted Neutral Grip Pull Up",
    "Neutral Grip Pull Ups",
    "Lat Pulldown",
    "Lat Pulldown Neutral Grip",
    "Reverse Grip Pulldown",
    "Close Grip Pulldown",
    "V Bar Pulldown",
    "Machine Lat Pulldown",
    "Single Arm Lat Pulldown",
    "Loop Band Lat Pulldown",
    "Straight Arm Pulldown",
    "Rope Straight Arm Pulldown",
    "Cable Crossover Lat Pulldown",
    "Cross-Body Lat Pull-Around",
  ],
  back_upper: [
    "Barbell Row",
    "Barbell Row Reverse Grip",
    "Dumbbell Row",
    "Dumbbell Bent Over Row",
    "Pendlay Row",
    "T Bar Row",
    "Landmine Row",
    "Meadows Row",
    "Cable Row",
    "Cable Row Wide Grip",
    "Machine Row",
    "Chest Supported T Row Neutral Grip",
    "Chest Supported T Row Wide Grip",
    "Plate-Loaded Chest Supported Row",
    "Plate-Loaded Chest Supported Row Closed Grip",
    "Plate-Loaded High Row",
    "Plate-Loaded Low Row",
    "Plate-Loaded Single Arm High Row",
    "Single Arm Cable Row",
    "Single Arm Chest Supported Cable Row",
    "Single Arm High Lat Row",
    "Single Arm Low Cable Row",
    "Incline Dumbbell Row",
    "Smith Machine Bent Over Row",
    "Inverted Row",
    "Inverted Row Reverse Grip",
    "TRX Inverted Row",
    "Kettlebell Row",
    "Kettlebell Alternating Row",
    "Loop Band Bent Over Row",
    "Loop Band Standing Single Arm Row",
    "Renegade Row",
    "Plate-Loaded Pullover",
    "SkiErg",
    "Swimming",
  ],
  chest: [
    "Barbell Bench Press",
    "Barbell Incline Bench Press",
    "Barbell Decline Bench Press",
    "Dumbbell Bench Press",
    "Dumbbell Incline Bench Press",
    "Decline Dumbbell Bench Press",
    "Single Arm Dumbbell Bench Press",
    "Machine Bench Press",
    "Plate-Loaded Chest Press",
    "Plate-Loaded Incline Chest Press",
    "Plate-Loaded Decline Chest Press",
    "Plate-Loaded Horizontal Bench Press",
    "Smith Machine Bench Press",
    "Smith Machine Decline Bench Press",
    "Smith Machine Incline Bench Press",
    "Floor Press",
    "Cable Crossover Fly",
    "Mid Cable Crossover Fly",
    "Dumbbell Fly",
    "Dumbbell Incline Fly",
    "Cable Crossover Flat Bench Fly",
    "Cable Crossover Incline Bench Fly",
    "Low Cable Chest Fly",
    "Machine Chest Fly",
    "Machine Bent Arm Chest Fly",
    "Seated Cable Fly",
    "Cable Chest Press",
    "Incline Cable Chest Press",
    "Cable Press-Around",
    "Chest Dip",
    "Close Grip Push Up",
    "Decline Push Up",
    "Diamond Push Up",
    "Hand Release Push Up",
    "Incline Push Up",
    "Push Up",
    "Push Up on Knees",
    "Dumbbell Squeeze Press",
    "Incline Dumbbell Squeeze Press",
    "Incline Svend Press",
    "Loop Band Push Up",
    "Loop Band Standing Chest Press",
    "Loop Band Standing Incline Chest Press",
    "Dumbbell Pullover",
    "TRX Chest Press"
  ],
  shoulders: [
    "Barbell Shoulder Press",
    "Dumbbell Lateral Raise",
    "Dumbbell Shoulder Press",
    "Seated Barbell Shoulder Press",
    "Arm Circles",
    "Arnold Press",
    "Cable Face Pull",
    "Cable Lateral Raise",
    "Dumbbell Lateral Raise Seated",
    "Leaning Lateral Raise",
    "Machine Reverse Fly",
    "Machine Shoulder Press",
    "Smith Machine Shoulder Press",
    "Barbell Front Raise",
    "Barbell High Pull",
    "BTB Cable Lateral Raise",
    "Cable Front Raise",
    "Cable Reverse Fly",
    "Cable Y Raise",
    "Clean and Press",
    "Cross Cable Rear Delt Fly",
    "Cross-Body Cable Y Raise",
    "Dumbbell Front Raise",
    "Dumbbell Hang Clean",
    "Dumbbell Hanging Lateral Raise",
    "Dumbbell Power Clean and Jerk",
    "Dumbbell Reverse Fly (Seated)",
    "Dumbbell Reverse Fly (Standing)",
    "Incline Dumbbell Y Raise",
    "Kettlebell Clean and Jerk",
    "Kettlebell Overhead Press",
    "Landmine Press",
    "Machine Lateral Raise",
    "Plate-Loaded Lateral Raise",
    "Plate-Loaded Shoulder Press",
    "Push Jerk",
    "Rope Front Raise",
    "Single Arm Landmine Press",
    "Single Dumbbell Power Clean",
    "Single Dumbbell Power Clean and Jerk",
    "Snatch",
    "Split Jerk",
    "Standing Dumbbell Shoulder Press",
    "Thruster",
    "Alternating Battle Rope",
    "Front Plate Raise",
    "Loop Band Face Pull",
    "Loop Band Lateral Raise",
    "Loop Band Overhead Press",
    "Pike Push Up",
    "Rope Slam",
    "TRX Rear Delt Fly"
  ],
  triceps: [
    "Assisted Dip",
    "Bench Dip",
    "Cable Cross-Body Tricep Extension",
    "Cable Overhead Tricep Extension",
    "Cable Overhead Tricep Extension (rope)",
    "Cable Rope Tricep Extension",
    "Cable Single Arm Tricep Extension",
    "Cable Single Arm Underhand Tricep Extension",
    "Cable Skullcrusher",
    "Cable Triceps Kickback",
    "Cable Underhand Tricep Pushdown",
    "Close Grip Bench Press",
    "Dumbbell Kickbacks",
    "Dumbbell Skullcrusher",
    "Dumbbell Tricep Extension",
    "EZ Bar Overhead Tricep Extension",
    "EZ Bar Skullcrusher",
    "Floor Tricep Extension",
    "Loop Band Tricep Extension",
    "Low Cable Overhead Tricep Extension",
    "Machine Tricep Dip",
    "Machine Tricep Extension",
    "Plate-Loaded Dip",
    "Single Arm Dumbbell Tricep Extension",
    "Single Arm Low Cable Overhead Tricep Extension",
    "Single Arm Overhead Cable Tricep Extension",
    "Smith Machine Close-Grip Bench Press",
    "Tate Press",
    "Tricep Dip",
    "Tricep Pushdown",
    "Tricep Pushdown V Bar",
    "TRX Tricep Extension",
    "Underhand Tricep Extension"
  ],
  abs: [
    "Ab Wheel Rollout",
    "Alternating Heel Touch",
    "Bear Plank",
    "Bicycle Crunch",
    "Cable Torso Rotation",
    "Cable Wood Chop High to Low",
    "Cable Wood Chop Low to High",
    "Cocoon Crunch",
    "Cross Body Mountain Climber",
    "Crunches",
    "Decline Crunch",
    "Decline Leg Raise",
    "Decline Oblique Crunch",
    "Decline Russian Twists",
    "Decline Sit Up",
    "Elbow to Knee Crunch",
    "Flutter Kicks",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Hanging Oblique Knee Raise",
    "High Plank Arm Reach",
    "Kettlebell Sit Up and Press",
    "Knee Raise",
    "Leg Raise",
    "Leg Raises with Stability Ball",
    "Machine Seated Crunch",
    "Mountain Climber",
    "Oblique Crunch",
    "Opposite Leg Toe Touch",
    "Plank",
    "Plank Jack",
    "Plank Shoulder Taps",
    "Plank Surrender",
    "Plate-Loaded Ab Crunch",
    "Reverse Crunch",
    "Rope Crunch",
    "Russian Twist",
    "Scissor Kick",
    "Side Plank",
    "Sit Up",
    "Stability Ball Crunch",
    "Stability Ball Plank Rollouts",
    "Stability Ball Pull In",
    "Toe Touches",
    "Torso Rotation",
    "TRX Ab Rollout",
    "TRX Fallout",
    "Tuck Crunch",
    "V Sit",
    "V Up",
    "Vertical Knee Raise",
    "Vertical Leg Raise"
  ],
  glutes: [
    "Barbell Glute Bridge",
    "Barbell Hip Thrust",
    "Dumbbell Glute Bridge",
    "Dumbbell Hip Thrust",
    "Plate-Loaded Hip Thrust",
    "Plate-Loaded Hip Thrust Belt Supported",
    "Single Leg Dumbbell Hip Thrust",
    "Single Leg Glute Bridge",
    "Smith Machine Hip Thrust",
    "Cable Kickback",
    "Cable Pull Through",
    "Chest Supported Cable Kickback",
    "Dumbbell Single Leg Glute Bridge",
    "Glute Bridge with mini band",
    "Glute Bridge with mini band (Abduction)",
    "Glute Ham Raise",
    "Kettlebell Swing",
    "Machine Glute Kickback",
    "Machine Standing Hip Extension",
    "Mini Band Kickbacks",
    "Plate-Loaded Glute Kickback",
    "Single Leg Smith Machine Reverse Kickback",
    "Smith Machine Reverse Kickback",
    "Stair Stepper"
  ],
  hamstrings: [
    "Barbell Romanian Deadlift",
    "Deadlift",
    "Dumbbell Good Morning",
    "Dumbbell Romanian Deadlift",
    "Good Morning",
    "Kettlebell Romanian Deadlift",
    "Kettlebell Suitcase Deadlift",
    "Loop Band Deadlift",
    "Loop Band Good Morning",
    "Plate-Loaded Deadlift",
    "Single Kettlebell Suitcase Deadlift",
    "Single Leg Romanian Deadlift",
    "Smith Machine Good Morning",
    "Smith Machine Romanian Deadlift",
    "Stiff Legged Deadlift",
    "Sumo Deadlift",
    "Trap Bar Deadlift",
    "Lying Hamstring Curl",
    "Plate-Loaded Standing Leg Curl",
    "Seated Leg Curl",
    "Single Leg Lying Hamstring Curl",
    "Single Leg Seated Curl"
  ],
  quads: [
    "Back Squat",
    "Belt Squat",
    "Box Squat",
    "Box Front Squat",
    "Dumbbell Goblet Squat",
    "Dumbbell Squat",
    "Front Squat",
    "Goblet Squat",
    "Hack Squat",
    "Hack Squat Machine",
    "Landmine Squat",
    "Pause Squat (bodyweight)",
    "Smith Machine Squat",
    "Smith Machine Front Squat",
    "Barbell Bulgarian Split Squat",
    "Barbell Lunge",
    "Barbell Split Squat",
    "Barbell Step Up",
    "Barbell Walking Lunges",
    "Bulgarian Split Squat",
    "Cable Step Up",
    "Dumbbell Bulgarian Split Squat",
    "Dumbbell Lunge",
    "Dumbbell Split Squat",
    "Dumbbell Step Up",
    "Dumbbell Walking Lunge",
    "Kettlebell Racked Split Squat",
    "Lunge",
    "Reverse Barbell Lunge",
    "Reverse Dumbbell Lunge",
    "Reverse Lunge",
    "Smith Machine Bulgarian Split Squat",
    "Smith Machine Split Squat",
    "Walking Lunge",
    "Leg Extension",
    "Leg Press",
    "Machine Leg Press",
    "Plate-Loaded Leg Extension",
    "Plate-Loaded Single Leg Extension",
    "Single Leg Extension",
    "Single Leg Press",
    "Vertical Leg Press",
    "Air Squat",
    "Alternating Lunge Jumps",
    "Box Jump",
    "Burpee",
    "Burpee Broad Jump",
    "Cossack Squat",
    "Dumbbell Sumo Squat",
    "Kettlebell Sumo Squat",
    "Lunge Jump",
    "Medicine Ball Lunge",
    "Overhead Squat",
    "Sissy Squat",
    "Sled Push",
    "Squat Jump",
    "TRX Pistol Squat",
    "Wall Ball",
    "Wall Sit"
  ],
  calves: [
    "Barbell Calf Raise",
    "Calf Raise",
    "Dumbbell Calf Raise",
    "Hip Loaded Calf Press Machine",
    "Plate-Loaded Angled Calf Press",
    "Plate-Loaded Standing Calf Raise",
    "Single Leg Standing Calf Raise",
    "Single Leg Standing Machine Calf Raise",
    "Smith Machine Calf Raise",
    "Standing Kettlebell Calf Raise",
    "Standing Machine Calf Raise",
    "Calf Press on Leg Press",
    "Plate-Loaded Seated Calf Raise",
    "Seated Calf Extension",
    "Jump Rope"
  ],
  lowerback: [
    "Back Extension",
    "Superman",
    "Machine Back Extension",
    "Alternating Superman",
    "Rack Pulls"
  ],
  forearms: [
    "Palms Down Barbell Wrist Curl",
    "Palms Up Barbell Wrist Curl",
    "Palms Up Dumbbell Wrist Curl",
    "Palms Down Dumbbell Wrist Curl"
  ],
  abductors: [
    "Cable Hip Abduction",
    "Machine Abduction",
    "Banded Seated Abduction",
    "Banded Side Lying Hip Abduction",
    "Clamshells",
    "Multi Hip Abduction"
  ],
  adductors: [
    "Machine Adduction",
    "Cable Hip Adduction",
    "Multi Hip Adduction"
  ],
};
