/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as WeightRouteImport } from './routes/weight'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FoodRouteImport } from './routes/food'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightRoute = WeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/weight': typeof WeightRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/weight': typeof WeightRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/weight': typeof WeightRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/food'
    | '/login'
    | '/plans'
    | '/profile'
    | '/quiz'
    | '/reset-password'
    | '/weight'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/food'
    | '/login'
    | '/plans'
    | '/profile'
    | '/quiz'
    | '/reset-password'
    | '/weight'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/food'
    | '/login'
    | '/plans'
    | '/profile'
    | '/quiz'
    | '/reset-password'
    | '/weight'
    | '/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FoodRoute: typeof FoodRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WeightRoute: typeof WeightRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FoodRoute: FoodRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WeightRoute: WeightRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
